import {
  ERole,
  ERoleScope,
  ERlsCheckType,
  PERMISSIONS_OBJECT,
} from './constants/data';
import { TABLES } from './constants/tables';
import type {
  PermissionDefinition,
  PermissionKeys,
  RoleDefinition,
  TableRlsPolicyConfig,
} from './data.types';

export { ERole, ERoleScope, ERlsCheckType, PERMISSIONS_OBJECT } from './constants/data';
export type { PermissionDefinition, PermissionKeys, RoleDefinition, TableRlsPolicyConfig } from './data.types';
export { parsePermissionKey } from './utils/data';

export const PERMISSIONS: PermissionDefinition[] = (
  Object.values(PERMISSIONS_OBJECT) as Array<Record<string, PermissionDefinition>>
).flatMap((group) => Object.values(group));

const P = PERMISSIONS_OBJECT;

/** Keys whose action is exactly `read` (catalogue convention for RLS SELECT–aligned reads). */
export const READ_PERMISSION_KEYS: PermissionKeys[] = PERMISSIONS.filter((entry) => entry.key.endsWith('.read')).map(
  (entry) => entry.key,
);

const memberPermissions: PermissionKeys[] = [
  P.org.read.key,
  P.org_member.read.key,
  P.org_invitation.read.key,
  P.org_role.read.key,
  P.org_group.read.key,
  P.org_group_member.create.key,
  P.org_group_role.create.key,
  P.project.read.key,
  P.project_member.read.key,
  P.job.read.key,
  P.job_member.read.key,
  P.job_invitation.read.key,
  P.conversation.read.key,
  P.conversation.create.key,
  P.conversation.update.key,
  P.conversation_member.read.key,
  P.conversation_member.create.key,
  P.conversation_invitation.read.key,
  P.message.read.key,
  P.message.create.key,
  P.vault_folder.read.key,
  P.vault_document.read.key,
  P.vault_document.create.key,
  P.vault_document.update.key,
  P.vault_document.upload.key,
  P.agent.read.key,
  P.agent.invoke.key,
  P.tool.read.key,
  P.task.read.key,
  P.task.create.key,
  P.task.update.key,
  P.task_checklist_item.read.key,
  P.task_checklist_item.create.key,
  P.task_checklist_item.update.key,
  P.form.read.key,
  P.form_response.read.key,
  P.knowledge_hub.read.key,
];

const externalUserPermissions: PermissionKeys[] = [
  P.job.read.key,
  P.job_member.read.key,
  P.job_invitation.read.key,
  P.project.read.key,
  P.conversation.read.key,
  P.conversation.create.key,
  P.conversation.update.key,
  P.conversation_member.read.key,
  P.conversation_invitation.read.key,
  P.message.read.key,
  P.message.create.key,
  P.vault_document.read.key,
  P.vault_document.upload.key,
  P.agent.read.key,
  P.agent.invoke.key,
  P.form.read.key,
  P.form_response.read.key,
  P.form_response.submit.key,
];

export const ROLES: RoleDefinition[] = [
  {
    key: ERole.Owner,
    label: 'Owner',
    description: 'Full organisation control across all catalogue permissions.',
    scope: ERoleScope.Organization,
    permissions: PERMISSIONS.map((permission) => permission.key),
  },
  {
    key: ERole.Admin,
    label: 'Admin',
    description: 'Organisation administration: all permissions in this catalogue.',
    scope: ERoleScope.Organization,
    permissions: PERMISSIONS.map((permission) => permission.key),
  },
  {
    key: ERole.Member,
    label: 'Member',
    description: 'Standard internal member: org directory, conversations, vault, agents, and related workflows.',
    scope: ERoleScope.Organization,
    permissions: memberPermissions,
  },
  {
    key: ERole.Support,
    label: 'Support',
    description: 'Internal support: handoffs, conversation context, and message sends where policy allows.',
    scope: ERoleScope.Internal,
    permissions: [
      P.org.read.key,
      P.support_handoff.create.key,
      P.support_handoff.read.key,
      P.support_handoff.update.key,
      P.conversation.read.key,
      P.conversation_member.read.key,
      P.message.read.key,
      P.message.create.key,
      P.agent.read.key,
      P.tool.read.key,
    ],
  },
  {
    key: ERole.ExternalUser,
    label: 'External User',
    description: 'Customer access via job and conversation membership without org administration.',
    scope: ERoleScope.Organization,
    permissions: externalUserPermissions,
  },
  {
    key: ERole.Viewer,
    label: 'Viewer',
    description: 'Read-only access to rows already visible under RLS.',
    scope: ERoleScope.Organization,
    permissions: READ_PERMISSION_KEYS.slice(),
  },
  {
    key: ERole.Auditor,
    label: 'Auditor',
    description: 'Read-only access across catalogue reads for review and compliance.',
    scope: ERoleScope.Organization,
    permissions: READ_PERMISSION_KEYS.slice(),
  },
  {
    key: ERole.BillingManager,
    label: 'Billing manager',
    description: 'Billing-focused access; org read and audit visibility until billing resources are modelled.',
    scope: ERoleScope.Organization,
    permissions: [P.org.read.key, P.audit_event.read.key],
  },
  {
    key: ERole.InternalDeveloper,
    label: 'Internal developer',
    description: 'Developer sandbox: conversations, vault, agents, and tools for draft flows.',
    scope: ERoleScope.Organization,
    permissions: [
      P.org.read.key,
      P.project.read.key,
      P.job.read.key,
      P.conversation.read.key,
      P.conversation.create.key,
      P.conversation.update.key,
      P.conversation_member.read.key,
      P.message.read.key,
      P.message.create.key,
      P.vault_folder.read.key,
      P.vault_document.read.key,
      P.vault_document.create.key,
      P.vault_document.upload.key,
      P.agent.read.key,
      P.agent.invoke.key,
      P.agent.manage.key,
      P.tool.read.key,
      P.tool.invoke.key,
    ],
  },
  {
    key: ERole.PluginDeveloper,
    label: 'Plugin developer',
    description: 'Integration-oriented read access to org roles, vault, and tools for package development.',
    scope: ERoleScope.Organization,
    permissions: [
      P.org.read.key,
      P.org_role.read.key,
      P.vault_folder.read.key,
      P.vault_document.read.key,
      P.tool.read.key,
      P.agent.read.key,
    ],
  },
  {
    key: ERole.Tester,
    label: 'Tester',
    description: 'Test-scope access to conversations, messages, documents, forms, and tasks.',
    scope: ERoleScope.Organization,
    permissions: [
      P.org.read.key,
      P.project.read.key,
      P.job.read.key,
      P.conversation.read.key,
      P.conversation.create.key,
      P.conversation_member.read.key,
      P.message.read.key,
      P.message.create.key,
      P.vault_folder.read.key,
      P.vault_document.read.key,
      P.vault_document.create.key,
      P.form.read.key,
      P.form.validate.key,
      P.task.read.key,
      P.task.create.key,
      P.tool.read.key,
      P.tool.invoke.key,
    ],
  },
];

export const TABLE_RLS_POLICY_CONFIG: TableRlsPolicyConfig[] = [
  {
    table: TABLES.PROFILES,
    checkType: ERlsCheckType.ProfileAccess,
    description: 'Profile self and org-scoped profile access.',
    classification: 'domain',
    permissions: {
      select: P.org_member.read.key,
      update: P.org_member.update.key,
    },
  },
  {
    table: TABLES.ORGANIZATIONS,
    checkType: ERlsCheckType.OrgPermission,
    description: 'Organisation root data.',
    classification: 'domain',
    permissions: {
      select: P.org.read.key,
      insert: P.org.create.key,
      update: P.org.update.key,
      delete: P.org.delete.key,
    },
  },
  {
    table: TABLES.ORGANIZATION_MEMBERS,
    checkType: ERlsCheckType.OrgPermission,
    description: 'Organisation members.',
    classification: 'domain',
    permissions: {
      select: P.org_member.read.key,
      insert: P.org_member.create.key,
      update: P.org_member.update.key,
      delete: P.org_member.delete.key,
    },
  },
  {
    table: TABLES.ORGANIZATION_INVITATIONS,
    checkType: ERlsCheckType.OrgPermission,
    description: 'Organisation invitations.',
    classification: 'domain',
    permissions: {
      select: P.org_invitation.read.key,
      insert: P.org_invitation.create.key,
      update: P.org_invitation.create.key,
      delete: P.org_invitation.revoke.key,
    },
  },
  {
    table: TABLES.ROLES,
    checkType: ERlsCheckType.OrgPermission,
    description: 'Role catalogue (system roles and per-organisation roles).',
    classification: 'domain',
    permissions: {
      select: P.org_role.read.key,
      insert: P.org_role.create.key,
      update: P.org_role.update.key,
      delete: P.org_role.delete.key,
    },
  },
  {
    table: TABLES.ROLE_PERMISSIONS,
    checkType: ERlsCheckType.OrgPermission,
    description: 'Role-permission linkage.',
    classification: 'domain',
    permissions: {
      select: P.org_role.read.key,
      insert: P.org_member_role.create.key,
      delete: P.org_member_role.delete.key,
    },
  },
  {
    table: TABLES.MEMBER_ROLES,
    checkType: ERlsCheckType.OrgPermission,
    description: 'Direct organisation member role assignments.',
    classification: 'domain',
    permissions: {
      select: P.org_member.read.key,
      insert: P.org_member_role.create.key,
      delete: P.org_member_role.delete.key,
    },
  },
  {
    table: TABLES.PERMISSIONS,
    checkType: ERlsCheckType.ReferenceRead,
    description: 'Global permission key catalogue.',
    classification: 'reference',
    permissions: { select: P.org_role.read.key },
  },
  {
    table: TABLES.GROUPS,
    checkType: ERlsCheckType.OrgPermission,
    description: 'Groups.',
    classification: 'domain',
    permissions: {
      select: P.org_group.read.key,
      insert: P.org_group.create.key,
      update: P.org_group.update.key,
      delete: P.org_group.delete.key,
    },
  },
  {
    table: TABLES.GROUP_MEMBERS,
    checkType: ERlsCheckType.OrgPermission,
    description: 'Group membership.',
    classification: 'domain',
    permissions: {
      select: P.org_group.read.key,
      insert: P.org_group_member.create.key,
      delete: P.org_group_member.delete.key,
    },
  },
  {
    table: TABLES.GROUP_ROLES,
    checkType: ERlsCheckType.OrgPermission,
    description: 'Group role assignments.',
    classification: 'domain',
    permissions: {
      select: P.org_group.read.key,
      insert: P.org_group_role.create.key,
      delete: P.org_group_role.delete.key,
    },
  },
  {
    table: TABLES.PROJECTS,
    checkType: ERlsCheckType.ProjectJobAccess,
    description: 'Projects.',
    classification: 'domain',
    permissions: {
      select: P.project.read.key,
      insert: P.project.create.key,
      update: P.project.update.key,
    },
  },
  {
    table: TABLES.PROJECT_MEMBERS,
    checkType: ERlsCheckType.ProjectJobAccess,
    description: 'Project membership.',
    classification: 'domain',
    permissions: {
      select: P.project_member.read.key,
      insert: P.project_member.create.key,
      delete: P.project_member.delete.key,
    },
  },
  {
    table: TABLES.JOBS,
    checkType: ERlsCheckType.ProjectJobAccess,
    description: 'Customer jobs.',
    classification: 'domain',
    permissions: {
      select: P.job.read.key,
      insert: P.job.create.key,
      update: P.job.update.key,
    },
  },
  {
    table: TABLES.JOB_MEMBERS,
    checkType: ERlsCheckType.ProjectJobAccess,
    description: 'Job membership.',
    classification: 'domain',
    permissions: {
      select: P.job_member.read.key,
      insert: P.job_member.create.key,
      delete: P.job_member.delete.key,
    },
  },
  {
    table: TABLES.JOB_INVITATIONS,
    checkType: ERlsCheckType.ProjectJobAccess,
    description: 'Job invitations.',
    classification: 'domain',
    permissions: {
      select: P.job_invitation.read.key,
      insert: P.job_invitation.create.key,
      update: P.job_invitation.create.key,
      delete: P.job_invitation.revoke.key,
    },
  },
  {
    table: TABLES.AGENTS,
    checkType: ERlsCheckType.AgentAccess,
    description: 'Agents.',
    classification: 'domain',
    permissions: {
      select: P.agent.read.key,
      insert: P.agent.create.key,
      update: P.agent.update.key,
      delete: P.agent.manage.key,
    },
  },
  {
    table: TABLES.PROJECT_AGENTS,
    checkType: ERlsCheckType.AgentAccess,
    description: 'Project agent links.',
    classification: 'domain',
    permissions: {
      select: P.agent.read.key,
      insert: P.agent.create.key,
      update: P.agent.update.key,
      delete: P.agent.manage.key,
    },
  },
  {
    table: TABLES.AGENT_VERSIONS,
    checkType: ERlsCheckType.AgentAccess,
    description: 'Agent version config rows.',
    classification: 'domain',
    permissions: {
      select: P.agent.read.key,
      insert: P.agent.create.key,
      update: P.agent.update.key,
      delete: P.agent.manage.key,
    },
  },
  {
    table: TABLES.AGENT_MEMBERS,
    checkType: ERlsCheckType.AgentAccess,
    description: 'Agent access grants.',
    classification: 'domain',
    permissions: {
      select: P.agent_member.read.key,
      insert: P.agent_member.create.key,
      update: P.agent_member.delete.key,
      delete: P.agent_member.delete.key,
    },
  },
  {
    table: TABLES.AGENT_INVITATIONS,
    checkType: ERlsCheckType.AgentAccess,
    description: 'Agent invitations.',
    classification: 'domain',
    permissions: {
      select: P.agent_invitation.read.key,
      insert: P.agent_invitation.create.key,
      update: P.agent_invitation.create.key,
      delete: P.agent_invitation.revoke.key,
    },
  },
  {
    table: TABLES.AGENT_INVOCATIONS,
    checkType: ERlsCheckType.AgentAccess,
    description: 'Agent invocation audit rows.',
    classification: 'domain',
    permissions: {
      select: P.agent.read.key,
      insert: P.agent.invoke.key,
      update: P.agent.invoke.key,
    },
  },
  {
    table: TABLES.CONVERSATIONS,
    checkType: ERlsCheckType.ConversationAccess,
    description: 'Conversations.',
    classification: 'domain',
    permissions: {
      select: P.conversation.read.key,
      insert: P.conversation.create.key,
      update: P.conversation.update.key,
    },
  },
  {
    table: TABLES.CONVERSATION_MEMBERS,
    checkType: ERlsCheckType.ConversationAccess,
    description: 'Conversation membership.',
    classification: 'domain',
    permissions: {
      select: P.conversation_member.read.key,
      insert: P.conversation_member.create.key,
      update: P.conversation_member.update.key,
      delete: P.conversation_member.delete.key,
    },
  },
  {
    table: TABLES.CONVERSATION_INVITATIONS,
    checkType: ERlsCheckType.ConversationAccess,
    description: 'Conversation invitations.',
    classification: 'domain',
    permissions: {
      select: P.conversation_invitation.read.key,
      insert: P.conversation_invitation.create.key,
      update: P.conversation_invitation.create.key,
      delete: P.conversation_invitation.revoke.key,
    },
  },
  {
    table: TABLES.MESSAGES,
    checkType: ERlsCheckType.ConversationAccess,
    description: 'Messages.',
    classification: 'domain',
    permissions: {
      select: P.message.read.key,
      insert: P.message.create.key,
      update: P.conversation.update.key,
      delete: P.conversation.update.key,
    },
  },
  {
    table: TABLES.MESSAGE_MENTIONS,
    checkType: ERlsCheckType.ConversationAccess,
    description: 'Mentions linked to messages.',
    classification: 'domain',
    permissions: {
      select: P.message.read.key,
      insert: P.message.create.key,
      delete: P.message.create.key,
    },
  },
  {
    table: TABLES.CONVERSATION_USER_STATE,
    checkType: ERlsCheckType.ConversationAccess,
    description: 'Per-user conversation state.',
    classification: 'domain',
    permissions: {
      select: P.conversation.read.key,
      insert: P.conversation.update.key,
      update: P.conversation.update.key,
    },
  },
  {
    table: TABLES.VAULT_FOLDERS,
    checkType: ERlsCheckType.OrgPermission,
    description: 'Vault folder tree.',
    classification: 'domain',
    permissions: {
      select: P.vault_folder.read.key,
      insert: P.vault_folder.create.key,
      update: P.vault_folder.update.key,
      delete: P.vault_folder.delete.key,
    },
  },
  {
    table: TABLES.DOCUMENTS,
    checkType: ERlsCheckType.DocumentAccess,
    description: 'Document metadata and lifecycle.',
    classification: 'domain',
    permissions: {
      select: P.vault_document.read.key,
      insert: P.vault_document.upload.key,
      update: P.vault_document.update.key,
      delete: P.vault_document.delete.key,
    },
  },
  {
    table: TABLES.DOCUMENT_CHUNKS,
    checkType: ERlsCheckType.DocumentAccess,
    description: 'RAG chunks.',
    classification: 'domain',
    permissions: {
      select: P.vault_document.read.key,
      insert: P.vault_document.reindex.key,
      update: P.vault_document.reindex.key,
      delete: P.vault_document.reindex.key,
    },
  },
  {
    table: TABLES.DOCUMENT_ACL,
    checkType: ERlsCheckType.DocumentAccess,
    description: 'Document ACL rows.',
    classification: 'domain',
    permissions: {
      select: P.vault_document.manage_permissions.key,
      insert: P.vault_document.manage_permissions.key,
      delete: P.vault_document.manage_permissions.key,
    },
  },
  {
    table: TABLES.DOCUMENT_CHUNK_SOURCES,
    checkType: ERlsCheckType.DocumentAccess,
    description: 'Document chunk provenance.',
    classification: 'domain',
    permissions: {
      select: P.vault_document.read.key,
      insert: P.vault_document.reindex.key,
    },
  },
  {
    table: TABLES.RETRIEVAL_EVENTS,
    checkType: ERlsCheckType.DocumentAccess,
    description: 'Retrieval audit events.',
    classification: 'domain',
    permissions: {
      select: P.audit_event.read.key,
      insert: P.tool.invoke.key,
    },
  },
  {
    table: TABLES.MESSAGE_ATTACHMENTS,
    checkType: ERlsCheckType.ConversationAccess,
    description: 'Message to document attachment.',
    classification: 'domain',
    permissions: {
      select: P.vault_document.read.key,
      insert: P.vault_document.upload.key,
      delete: P.vault_document.delete.key,
    },
  },
];
